// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgjCw0GcdJehnNrPdVGtEHtSrOVuuJxsw',
    appId: '1:1076162529140:web:ce94a51a319a42b2e3ce21',
    messagingSenderId: '1076162529140',
    projectId: 'alert-system-for-gaps',
    authDomain: 'alert-system-for-gaps.firebaseapp.com',
    storageBucket: 'alert-system-for-gaps.appspot.com',
    measurementId: 'G-NNEV23K7X4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeSHxWpyOgIGEBZPrQdwvwnTKF_lRaNpo',
    appId: '1:1076162529140:android:bad0490e4ccfae94e3ce21',
    messagingSenderId: '1076162529140',
    projectId: 'alert-system-for-gaps',
    storageBucket: 'alert-system-for-gaps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF2QqeWD6mugR9JfgUSjHPzYA6w5SPK9I',
    appId: '1:1076162529140:ios:1b19c513c544e52ee3ce21',
    messagingSenderId: '1076162529140',
    projectId: 'alert-system-for-gaps',
    storageBucket: 'alert-system-for-gaps.appspot.com',
    iosBundleId: 'com.example.alertSystemForGaps',
  );
}
